# Generated by Django 5.1.5 on 2025-01-19 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_uploadmodel_alter_category_id_alter_course_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='imagUrl',
        ),
        migrations.AddField(
            model_name='course',
            name='image',
            field=models.ImageField(default='', upload_to='images'),
        ),
    ]
